### PR TITLE
storage: nil out transaction .Error on unknown result

### LINKED ISSUE #704: runtime tx unexpected fields
cc @matevz @csillag 

https://explorer.oasis.io/mainnet/sapphire/tx/7224d59e6b74d9b2caf55ab40dfe0757cef4f71c66d3a7aba3de1d267d2ea409

this tx has `error` set while the status is unknown. api should clear out the error

also its method is blank, which isn't right. allegedly it's supposed to be accounts.Transfer

### PR DESCRIPTION
**Pull request by pro-wh**
Unknown -> .Success = nil -> .Error = nil
Ok -> .Success = common.Ptr(true) -> .Error = nil
Failed -> .Success = common.Ptr(false) -> .Error not nil

is my understanding for today

fixes #704, unexpeced non-nil .Error

### CODE REVIEW

File: storage/client/client.go [hunk 1]
```diff
@@ -1531,7 +1531,7 @@ func (c *StorageClient) RuntimeTransactions(ctx context.Context, p apiTypes.GetR
 		); err != nil {
 			return nil, wrapError(err)
 		}
-		if t.Success != nil && *t.Success {
+		if t.Success == nil || *t.Success {
```
Comment (Andrew7234) [inline storage/client/client.go:1534]:
```suggestion
               // If the transaction was encrypted or was successful, no error information is available.
		if t.Success == nil || *t.Success {
```

**Review by Andrew7234 — APPROVED** [review]
Thanks! Mind also updating the [runtime analyzer](https://github.com/oasisprotocol/nexus/blob/main/analyzer/runtime/runtime.go#L302) to use pointers for `error_code` and `error_module` as well?

**Comment by pro-wh** [comment]
k let's update analyzer too

**Comment by pro-wh** [comment]
separate PR since this is already reviewed tho

File: storage/client/client.go (hunk 1 above)
Comment (pro-wh) [reply storage/client/client.go:1538]: added
